In [2]:
import pandas as pd
import numpy as np
from numpy.random import randn


In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[1:5]=100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
slice_arr = arr[5:]
slice_arr

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [16]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]

In [19]:
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [20]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [22]:
np.random.seed(101)

In [23]:
np.random.randn(25)

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
       -0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206,
        0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722,
        0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889,
        0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072])

In [24]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns ='W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [4]:
df2 = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns = 'W X Y Z'.split())
df2

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [5]:
df2['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [7]:
df[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [9]:
type(df['W'])

pandas.core.series.Series

In [10]:
df['New'] = df['W'] + df['Y']
df

W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [11]:
df2.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [12]:
df.loc[['A', 'B'], ['W', 'Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [13]:
df2 > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [14]:
df.reset_index()

index         W         X         Y         Z       New
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
4     E  0.190794  1.978757  2.605967  0.683509  2.796762

In [16]:
newid = 'CA NY WY OR CO'.split()
df['States'] = newid
df.set_index('States')

W         X         Y         Z       New
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762

In [18]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
heir_index = list(zip(outside, inside))
heir_index = pd.MultiIndex.from_tuples(heir_index)
heir_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [20]:
df = pd.DataFrame(np.random.randn(6,2), index=heir_index, columns=['A', 'B'])
df

A         B
G1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
G2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

In [21]:
df.loc['G1']

A         B
1  0.147027 -0.479448
2  0.558769  1.024810
3 -0.925874  1.862864